### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: org.boon.Boon.configurableLogger(Ljava/lang/Class;)Lorg/boon/Logger;

### ISSUE THREAD

**Issue by lavanya87** [boonproject/boon#277]
I am using boon etcd for implementing a service registry. The pom.xml has the following dependencies:
      
      <dependency>
      <groupId>io.fastjson</groupId>
      <artifactId>boon</artifactId>
      <version>0.11</version>
      </dependency>

      <dependency>
      <groupId>io.fastjson</groupId>
      <artifactId>etcd-client</artifactId>
      <version>0.29</version>
      </dependency>

I then copied the ExampleMain.java file and tried running it, but i am getting the following exception:

Exception in thread "main" java.lang.NoSuchMethodError: org.boon.Boon.configurableLogger(Ljava/lang/Class;)Lorg/boon/Logger;
	at org.boon.etcd.EtcdClient.<init>(EtcdClient.java:108)
	at org.boon.etcd.ClientBuilder.createClient(ClientBuilder.java:140)
	at serviceregistry.ExampleMain.main(ExampleMain.java:58)

Am i using the correct version of dependency? Please suggest how to resolve this issue.

Thanks!
Lavanya

**Comment by RichardHightower** [comment]
Try building boon and depending on a snapshot.
