### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.boon.json.implementation.JsonParserLax

### ISSUE THREAD

**Issue by AShynkevich** [boonproject/boon#291]
Hello. I've executed follow code:

 ```
...
private ObjectMapper objectMapper = JsonFactory.create();

@ResponseBody
    @RequestMapping(value = "post/update", method = RequestMethod.POST)
    public String updatePost(@RequestBody String body) {
        Post post = objectMapper.readValue(body, Post.class);
        postService.updatePost(post);
        return "done";
    }
...
```
and exception has been appeared:
```
WARNING: /protected/post/update
java.lang.NoClassDefFoundError: Could not initialize class org.boon.json.implementation.JsonParserLax
	at org.boon.json.JsonMappingParser.<init>(JsonMappingParser.java:85)
	at org.boon.json.JsonParserFactory.create(JsonParserFactory.java:228)
	at org.boon.json.implementation.ObjectMapperImpl.readValue(ObjectMapperImpl.java:67)
	at com.appspot.beatbox.controller.AdminController.updatePost(AdminController.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:115)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:919)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:851)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)

```

May be cause is libs conflict, i'm not sure. This my Gradle configuration:

```
dependencies {
    compile 'commons-collections:commons-collections:3.2.1'
	compile 'commons-io:commons-io:2.4'
    compile 'org.apache.commons:commons-lang3:3.3.2'
	compile 'commons-lang:commons-lang:2.6'
	compile 'commons-dbcp:commons-dbcp:1.4'
	
	compile 'org.springframework:spring-webmvc:3.2.13.RELEASE'
	compile 'org.springframework:spring-core:3.2.13.RELEASE'
	compile 'org.springframework:spring-tx:3.2.13.RELEASE'
	compile 'org.springframework:spring-aop:3.2.13.RELEASE'
	compile 'org.springframework:spring-context:3.2.13.RELEASE'
	compile 'org.springframework:spring-jdbc:3.2.13.RELEASE'
	compile 'org.springframework:spring-context-support:3.2.13.RELEASE'	
	compile 'org.springframework:spring-beans:3.2.13.RELEASE'	

	compile 'org.springframework.security:spring-security-web:3.2.5.RELEASE'
	compile 'org.springframework.security:spring-security-config:3.2.5.RELEASE'
	compile 'org.springframework.security:spring-security-taglibs:3.2.5.RELEASE'

	//boon
	compile 'io.fastjson:boon:0.30'
	//other
	compile 'javax.mail:mail:1.4.7'
	compile 'org.slf4j:slf4j-api:1.7.7'
	compile 'org.slf4j:slf4j-log4j12:1.7.7'
	compile 'org.freemarker:freemarker:2.3.19'
	compile 'com.fasterxml.jackson.core:jackson-databind:2.4.1'
	compile 'org.mybatis:mybatis:3.2.7'
	compile 'org.mybatis:mybatis-spring:1.2.2'
	compile 'com.h2database:h2:1.4.179'

	//servlet
    compile 'javax.servlet:servlet-api:2.5'
	providedCompile 'javax.servlet.jsp:jsp-api:2.1'
	providedCompile 'javax.servlet:jstl:1.2'

	//appEngineSDK
	appengineSdk "com.google.appengine:appengine-java-sdk:${appEngineVersion}"
    compile "com.google.appengine:appengine-endpoints:${appEngineVersion}"
    compile "com.google.appengine:appengine-endpoints-deps:${appEngineVersion}"
	//objectify
	compile "com.googlecode.objectify:objectify:5.1.4"
}
```

**Comment by RichardHightower** [comment]
Seems like a classloader issue in your spring app. 
You might be pulling in more than one boon jar.

**Comment by 1aman2** [comment]
java.lang.NoClassDefFoundError: org/boon/json/JsonFactory
Getting this error
