### ISSUE TITLE
etcd client error

### ISSUE THREAD

**Issue by py8765** [boonproject/boon#295]
```
Response response;
Etcd client = ClientBuilder.builder().hosts(URI.create("http://localhost:4001")).createClient();
response = client.get("message");

```

I start the etcd server and when I try to run the code above, the error is 

Exception in thread "main" org.boon.etcd.exceptions.ConnectionException: Connection exception for key message
	at org.boon.etcd.EtcdClient.getResponse(EtcdClient.java:678)
	at org.boon.etcd.EtcdClient.request(EtcdClient.java:251)
	at org.boon.etcd.EtcdClient.get(EtcdClient.java:571)
	at com.netease.pomelo.etcd.Test.main(Test.java:19)

**Comment by py8765** [comment]
my fault; server open 127.0.0.1
